import AppKit
import Foundation

// MARK: - BackgroundSyncTrigger

/// What prompted the refresh to be considered.
///
/// The distinction is not cosmetic: a reactivation arrives whenever the user comes back to the app,
/// which can be dozens of times an hour, so it is throttled on its own account as well as by the
/// interval. A timer tick needs no such guard — its cadence *is* the throttle.
enum BackgroundSyncTrigger: Sendable {
    /// The repeating interval elapsed.
    case timer
    /// The app became active, or the machine woke.
    case reactivation
}

// MARK: - BackgroundSyncMonitoring

/// Starts and stops periodic vault refresh, and asks whether a tick should become a sync.
///
/// A protocol so `RootViewModel` can be tested without installing a `Timer` and two notification
/// observers: that AppKit wiring is the part a unit test cannot exercise, and it is exactly what
/// this seam removes from the ViewModel's tests.
@MainActor
protocol BackgroundSyncMonitoring: AnyObject {

    /// Called when a tick the decision allowed should become a sync. The owner sets this.
    var onTick: ((BackgroundSyncTrigger) -> Void)? { get set }

    /// Begins observing the interval, app activation and machine wake. Idempotent.
    func start()

    /// Stops observing and releases the timer. Idempotent.
    func stop()

    /// Whether a tick should become a sync right now.
    ///
    /// Answered by the monitor rather than by the caller because the interval and the reactivation
    /// throttle are the monitor's own state; the caller supplies only what it knows about the
    /// session.
    ///
    /// - Parameters:
    ///   - trigger: what prompted the tick.
    ///   - isUnlocked: whether the vault is open. A refresh with the vault locked is never allowed.
    ///   - isBusy: whether the session is mid-edit or mid-mutation. A refresh would replace the
    ///     item list and the selected item underneath the user's work.
    ///   - lastSuccessfulSyncAt: when the vault last synced from the server, or `nil` if it never
    ///     has. Deliberately the last *success*, not the last *attempt* — see `shouldSync(at:…)`.
    func shouldSync(trigger: BackgroundSyncTrigger,
                    isUnlocked: Bool,
                    isBusy: Bool,
                    lastSuccessfulSyncAt: Date?) -> Bool
}

// MARK: - BackgroundSyncMonitor

/// Refreshes the vault on a timer and when the app or the machine comes back, while the session is
/// unlocked.
///
/// **Why a timer at all.** The vault is fetched at unlock and then held for the life of the session,
/// so a session nobody touches keeps the vault it opened with. That failure mode is the dangerous
/// kind: the vault is unlocked and *looks current*.
///
/// **Why reactivation matters more than the interval.** The common case is not "the app has been
/// open for five minutes"; it is "the laptop was shut, reopened this morning, and the vault is a day
/// old". A pure interval gets there too, after up to five minutes of the user working against stale
/// data. So activation and wake are triggers in their own right.
///
/// **Testability.** The clock is injected and the decision is `shouldSync(…)`, a pure function of it
/// and the supplied state. The AppKit wiring lives entirely in `start()`/`stop()` and is never
/// exercised by tests: testing a five-minute interval by waiting five minutes is not a test anyone
/// would keep.
@MainActor
final class BackgroundSyncMonitor: BackgroundSyncMonitoring {

    /// How long a vault may go unrefreshed while unlocked.
    ///
    /// The default vault timeout is 15 minutes, so a longer interval would frequently never fire at
    /// all — the vault would lock first and the session to refresh would be gone. Five minutes gives
    /// at least two ticks inside a default-configured idle session, and more in a session that is
    /// being used, since activity postpones the lock.
    ///
    /// A constant rather than a setting: the difference between five and fifteen minutes of
    /// staleness is not something a user can evaluate without knowing the sync cost, and both are
    /// fine. If it needs to change, it changes here.
    static let interval: TimeInterval = 300

    /// The minimum gap between two reactivation-triggered evaluations.
    ///
    /// Without it, switching windows would evaluate on every switch. The evaluation is cheap, but the
    /// sync it can green-light is not, and the interval alone does not bound this trigger: a
    /// reactivation is generated by the user, not by the clock.
    static let reactivationThrottle: TimeInterval = 30

    var onTick: ((BackgroundSyncTrigger) -> Void)?

    /// Whether the timer and observers are installed. Exposed so the installed state is assertable;
    /// the installation itself is AppKit's and is not observable from a unit test.
    private(set) var isRunning = false

    private let now: () -> Date

    /// When a reactivation trigger was last *evaluated* — not last acted on.
    ///
    /// Recording a refused evaluation is deliberate: the throttle exists to bound how often the
    /// question is asked, and a burst of window switches is exactly the case it is for. Refusing to
    /// record would let a burst past the interval the moment it elapses.
    private var lastReactivationAt: Date?

    // nonisolated(unsafe) because `deinit` is always nonisolated in Swift 6 and neither `Timer` nor
    // an observer token is Sendable. Both are only ever mutated on MainActor.
    nonisolated(unsafe) private var timer: Timer?
    nonisolated(unsafe) private var activationObserver: NSObjectProtocol?
    nonisolated(unsafe) private var wakeObserver: NSObjectProtocol?

    init(now: @escaping () -> Date = Date.init) {
        self.now = now
    }

    deinit {
        timer?.invalidate()
        if let activationObserver { NotificationCenter.default.removeObserver(activationObserver) }
        if let wakeObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(wakeObserver)
        }
    }

    // MARK: - Lifecycle

    func start() {
        guard !isRunning else { return }

        timer = Timer.scheduledTimer(withTimeInterval: Self.interval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.emit(.timer) }
        }

        activationObserver = NotificationCenter.default.addObserver(
            forName: NSApplication.didBecomeActiveNotification,
            object:   nil,
            queue:    .main
        ) { [weak self] _ in
            // Notification handlers on the main queue run on the main thread. `assumeIsolated`
            // states that rather than hopping through a Task.
            MainActor.assumeIsolated { self?.emit(.reactivation) }
        }

        // `NSWorkspace` posts on its own centre, not the default one.
        wakeObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didWakeNotification,
            object:   nil,
            queue:    .main
        ) { [weak self] _ in
            MainActor.assumeIsolated { self?.emit(.reactivation) }
        }

        isRunning = true
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        if let activationObserver {
            NotificationCenter.default.removeObserver(activationObserver)
            self.activationObserver = nil
        }
        if let wakeObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(wakeObserver)
            self.wakeObserver = nil
        }
        // The next unlock starts a fresh session; carrying the previous session's throttle across
        // would suppress the first reactivation of the new one for no reason.
        lastReactivationAt = nil
        isRunning = false
    }

    // MARK: - The decision

    /// The whole rule set, as a function of the clock and the session's state.
    ///
    /// Deliberately changes nothing: asking the question must not change the answer for the next
    /// caller. The one piece of state a caller may want to thread in is the reactivation throttle,
    /// which is why it is an explicit parameter rather than read from `self` here.
    ///
    /// Note what is **not** an input: the time of the last *attempt*. The interval is measured from
    /// the last successful sync, so a run of failures cannot shorten it and turn a server outage
    /// into a retry storm. There is no attempt-based clock for a failure to reset, and there is
    /// deliberately nowhere to add one.
    static func shouldSync(at date: Date,
                           trigger: BackgroundSyncTrigger,
                           isUnlocked: Bool,
                           isBusy: Bool,
                           lastSuccessfulSyncAt: Date?,
                           lastReactivationAt: Date?) -> Bool {
        // Locked: the refresh would need the user key resident to decrypt the response, which is
        // the exact state `lockVault()` exists to destroy. An unattended refresh is not worth a
        // weakened lock guarantee.
        guard isUnlocked else { return false }

        // Busy: completing a sync replaces the item list and re-reads the selected item from the
        // store. Under an open draft, or between a write and the store's update, that is destructive
        // rather than merely redundant. Checked before the interval so a long-open sheet cannot
        // "bank" elapsed time and fire the instant it closes.
        guard !isBusy else { return false }

        if trigger == .reactivation, let lastReactivationAt,
           date.timeIntervalSince(lastReactivationAt) < reactivationThrottle {
            return false
        }

        // A vault that has never synced has no baseline to measure an interval from, so it is
        // eligible. The timer's own cadence bounds this — one attempt per tick, not a loop.
        if let lastSuccessfulSyncAt,
           date.timeIntervalSince(lastSuccessfulSyncAt) < interval {
            return false
        }

        return true
    }

    func shouldSync(trigger: BackgroundSyncTrigger,
                    isUnlocked: Bool,
                    isBusy: Bool,
                    lastSuccessfulSyncAt: Date?) -> Bool {
        let date = now()
        let verdict = Self.shouldSync(
            at: date,
            trigger: trigger,
            isUnlocked: isUnlocked,
            isBusy: isBusy,
            lastSuccessfulSyncAt: lastSuccessfulSyncAt,
            lastReactivationAt: lastReactivationAt
        )
        if trigger == .reactivation { lastReactivationAt = date }
        return verdict
    }

    // MARK: - Private

    /// Names the fact that a trigger happened. Whether that becomes a sync is the caller's question
    /// — it holds the session state — so this is only a notification, not a decision.
    private func emit(_ trigger: BackgroundSyncTrigger) {
        onTick?(trigger)
    }
}
