#!/usr/bin/env bash
# gen-rsa-kat.sh — Generates RSA-OAEP-SHA1 known-answer test fixtures for
# OrgKeyCryptoKATTests.testUnwrapOrgKey_knownVector() and patches the test file.
#
# Algorithm: RSA-2048, OAEP padding with SHA-1 hash and SHA-1 MGF1 — matching
# the Bitwarden protocol (Security Whitepaper §4, "Organization Key Wrapping")
# and the Security.framework call in PrizmCryptoServiceImpl.unwrapOrgKey
# (.rsaEncryptionOAEPSHA1 = OAEP + SHA-1 hash + SHA-1 MGF1).
#
# Requires: python3 with the 'cryptography' package.
#   Install: pip3 install cryptography
#
# Usage (run from repo root or any directory):
#   bash openspec/changes/org-support/test-fixtures/gen-rsa-kat.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
TEST_FILE="$REPO_ROOT/Prizm/PrizmTests/Data/OrgKeyCryptoKATTests.swift"

# ── Preflight ─────────────────────────────────────────────────────────────────

if ! command -v python3 &>/dev/null; then
    echo "error: python3 is required." >&2
    exit 1
fi

if ! python3 -c "import cryptography" 2>/dev/null; then
    echo "error: the Python 'cryptography' package is required." >&2
    echo "  Install with: pip3 install cryptography" >&2
    exit 1
fi

if [[ ! -f "$TEST_FILE" ]]; then
    echo "error: test file not found: $TEST_FILE" >&2
    exit 1
fi

# ── Generate and patch ────────────────────────────────────────────────────────

python3 - "$TEST_FILE" <<'PYTHON'
import sys, re, base64, warnings

# Suppress SHA1 deprecation warnings — SHA-1 is the Bitwarden protocol
# requirement for RSA-OAEP key transport, not a free choice.
warnings.filterwarnings("ignore", category=DeprecationWarning)

from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.asymmetric.padding import OAEP, MGF1
from cryptography.hazmat.primitives import hashes, serialization

test_file = sys.argv[1]

# ── 1. RSA-2048 key pair ──────────────────────────────────────────────────────
print("Generating RSA-2048 key pair…")
private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

# ── 2. PKCS#8 DER → base64 (the format Security.framework expects after
#       PrizmCryptoServiceImpl.decryptRSAPrivateKey strips the EncString) ──────
private_der = private_key.private_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption(),
)
private_key_b64 = base64.b64encode(private_der).decode()
print(f"  Private key (PKCS#8 DER, base64): {len(private_key_b64)} chars")

# ── 3. RSA-OAEP-SHA1 encrypt 64 zero-bytes → Type-4 EncString ────────────────
#    SHA-1 for both the OAEP hash and the MGF1 hash — matching
#    kSecKeyAlgorithmRSAEncryptionOAEPSHA1 in Security.framework.
plaintext = bytes(64)  # 64 zero-bytes: first 32 = encKey, last 32 = macKey
ciphertext = private_key.public_key().encrypt(
    plaintext,
    OAEP(mgf=MGF1(algorithm=hashes.SHA1()), algorithm=hashes.SHA1(), label=None),
)
enc_org_key = "4." + base64.b64encode(ciphertext).decode()
print(f"  EncOrgKey (Type-4): {enc_org_key[:40]}…")

# ── 4. Format private key as Swift multiline string with \ continuations ───────
LINE_WIDTH = 76
chunks = [private_key_b64[i:i + LINE_WIDTH]
          for i in range(0, len(private_key_b64), LINE_WIDTH)]
formatted_key = "\n".join(
    f"    {chunk}" + ("\\" if idx < len(chunks) - 1 else "")
    for idx, chunk in enumerate(chunks)
)

# ── 5. Patch the test file ────────────────────────────────────────────────────
with open(test_file, "r") as f:
    content = f.read()

# Replace testRSAPrivateKeyPKCS8Base64 multiline value
key_pat = r'(private static let testRSAPrivateKeyPKCS8Base64 = """\n).*?(    """)'
key_rep = f"\\1{formatted_key}\n\\2"
content, n = re.subn(key_pat, key_rep, content, flags=re.DOTALL)
if n == 0:
    print("error: could not find testRSAPrivateKeyPKCS8Base64", file=sys.stderr)
    sys.exit(1)

# Replace testEncOrgKey value
enc_pat = r'(private static let testEncOrgKey = )"[^"]*"'
content, n = re.subn(enc_pat, f'\\1"{enc_org_key}"', content)
if n == 0:
    print("error: could not find testEncOrgKey", file=sys.stderr)
    sys.exit(1)

# Remove the placeholder NOTE comment (no longer accurate after generation)
content = re.sub(
    r"    /// NOTE: This fixture is intentionally left as a placeholder\.\n"
    r"    /// The actual value must be generated by running the offline key-generation script\n"
    r"    /// in `[^`]+`[^\n]*\.\n"
    r"    /// The test will remain RED until both the fixture and the implementation are complete\.\n",
    "",
    content,
)

with open(test_file, "w") as f:
    f.write(content)

print(f"  Patched: {test_file}")
print()
print("Done. Run: xcodebuild test -project Prizm/Prizm.xcodeproj -scheme Prizm "
      "-destination 'platform=macOS' -only-testing PrizmTests/OrgKeyCryptoKATTests")
PYTHON
